### ISSUE TITLE
请问Theme名字

### ISSUE THREAD

**Issue by Konfido** [WinMin/Sw-blog#3]
https://bestwing.me/ 十分心水这个简洁耐看的blog主题了🤩请问下，你是用的Hexo/Jekyll的某个主题吗？还是说是自己的设计？能否考虑下开源或分享下代码呢？

<img width="842" alt="2019-03-04 17 39 08" src="https://user-images.githubusercontent.com/25447610/53724316-9660dd80-3ea4-11e9-82ee-e2ad1e801807.png">

**Comment by winmin** [comment]
hexo.io 就有On Mar 4, 2019, at 5:49 PM, Konfido <notifications@github.com> wrote:https://bestwing.me/ 十分心水这个简洁耐看的blog主题了🤩请问下，你是用的Hexo/Jekyll的某个主题吗？还是说是自己的设计？能否考虑下开源或分享下代码呢？—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by winmin** [comment]
On Mar 4, 2019, at 5:49 PM, Konfido <notifications@github.com> wrote:https://bestwing.me/ 十分心水这个简洁耐看的blog主题了🤩请问下，你是用的Hexo/Jekyll的某个主题吗？还是说是自己的设计？能否考虑下开源或分享下代码呢？—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

Hexo .io 能找到这个主题

**Comment by Konfido** [comment]
好的，终于找到了，Cactus
